management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  tracing:
    enabled: true
    sampling.probability: 1.0
    otlp.tracing:
      endpoint: http://tempo:4317
      protocol: grpc

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/rento?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
